# Generated by Django 5.2.6 on 2025-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_by',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
