apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app
          image: your-dockerhub-username/messaging-app:latest  # Replace with your actual image
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              value: "messaging_db"
            - name: MYSQL_USER
              value: "messaging_user"
            - name: MYSQL_PASSWORD
              value: "securepassword"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
